[package]
name = "keyboard-service"
version = "0.1.0"
edition = "2024"
description = "Keyboard service implementation"
repository = "https://github.com/OpenDevicePartnership/embedded-services"
rust-version.workspace = true
license = "MIT"

[package.metadata.cargo-machete]
ignored = ["defmt", "log"]

[dependencies]
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }
embassy-sync.workspace = true
embassy-time.workspace = true
embedded-services.workspace = true
embedded-hal.workspace = true
odp-service-common.workspace = true
typenum.workspace = true
bitflags.workspace = true
keyberon = { git = "https://github.com/TeXitoi/keyberon", rev = "362c209f729d05505abb1984a0ddb321ec9ebf53" }

[dev-dependencies]
critical-section = { workspace = true, features = ["std"] }
embassy-futures.workspace = true
embassy-time = { workspace = true, features = ["std", "generic-queue-8"] }

[features]
default = []
defmt = [
    "dep:defmt",
    "embedded-services/defmt",
    "embassy-time/defmt",
    "embassy-sync/defmt",
]
log = [
    "dep:log",
    "embedded-services/log",
    "embassy-time/log",
    "embassy-sync/log",
]

[lints]
workspace = true
